apiVersion: v1
kind: Namespace
metadata:
  name: php-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: php-app
  name: php-php
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-app
    spec:
      containers:
      - image: 730335550052.dkr.ecr.ap-south-1.amazonaws.com/rajack:latest
        imagePullPolicy: Always
        name: php-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: php-app
  name: php-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: php-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: php-app
  name: php-app
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: " "
    alb.ingress.kubernetes.io/healthcheck-path: "/"
    alb.ingress.kubernetes.io/subnets: "subnet-09c64fc05269ed06b,subnet-subnet-084b671d320788c6d"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - host: "*.amazonaws.com"
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: php-app
              port:
                number: 80
