apiVersion: v1
kind: Namespace
metadata:
  name: php-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: php-app
  name: deployment-php
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: php-app
  replicas: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: php-app
    spec:
      containers:
      - image: 730335550052.dkr.ecr.ap-south-1.amazonaws.com/rajack:latest
        imagePullPolicy: Always
        name: php-app
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: php-app
  name: php-app
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: php-app
